version: '3'
services:
        cql_adminer_adapter:
                image: covenantsql/covenantsql:latest
                container_name: cql_adminer_adapter
                restart: always
                logging:
                        driver: 'json-file'
                        options:
                                max-size: '10m'
                environment:
                        COVENANT_ROLE: adapter
                        COVENANT_CONF: /etc/testnet_conf/config.yaml
                        COVENANTSQL_ADAPTER_ADDR: 0.0.0.0:80
                volumes:
                        - ~/.cql/private.key:/etc/testnet_conf/private.key
                        - ~/.cql/config.yaml:/etc/testnet_conf/config.yaml
        cql_adminer:
                image: covenantsql/adminer:latest
                container_name: cql_adminer
                restart: always
                ports:
                        - 11149:80
                logging:
                        driver: 'json-file'
                        options:
                                max-size: '10m'
                links:
                        - cql_adminer_adapter
                environment:
                        CQL_ADAPTER_SERVER: cql_adminer_adapter

